// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1tZDgSQZvFJlIW4GjwRPO3Rsyf0eK98',
    appId: '1:10216121301:web:70a87b4c92be56b09f935c',
    messagingSenderId: '10216121301',
    projectId: 'task-list-61dc3',
    authDomain: 'task-list-61dc3.firebaseapp.com',
    storageBucket: 'task-list-61dc3.firebasestorage.app',
    measurementId: 'G-96B056VHDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbsMl5kMDQyl9Dble_k0diXYotZptO48',
    appId: '1:10216121301:android:d3750fcc020c4a989f935c',
    messagingSenderId: '10216121301',
    projectId: 'task-list-61dc3',
    storageBucket: 'task-list-61dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52E3vm9fVPuvn1lMkUMjavF9w9y8eiiA',
    appId: '1:10216121301:ios:8e53c7efb9e16a4a9f935c',
    messagingSenderId: '10216121301',
    projectId: 'task-list-61dc3',
    storageBucket: 'task-list-61dc3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWithCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD52E3vm9fVPuvn1lMkUMjavF9w9y8eiiA',
    appId: '1:10216121301:ios:8e53c7efb9e16a4a9f935c',
    messagingSenderId: '10216121301',
    projectId: 'task-list-61dc3',
    storageBucket: 'task-list-61dc3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWithCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe1tZDgSQZvFJlIW4GjwRPO3Rsyf0eK98',
    appId: '1:10216121301:web:95c64bef37e2e6bb9f935c',
    messagingSenderId: '10216121301',
    projectId: 'task-list-61dc3',
    authDomain: 'task-list-61dc3.firebaseapp.com',
    storageBucket: 'task-list-61dc3.firebasestorage.app',
    measurementId: 'G-P2CHL0JTHB',
  );
}
